### ISSUE TITLE
can it work

### ISSUE THREAD

**Issue by PapadeStonne** [liuzhenboo/MAV_Search_Trail#1]
Hi liuzhenbo,
Big fan of your work. Is there any ducument about your work? Maybe a demo.
Many thanks!

**Comment by liuzhenboo** [comment]
Thank you for your attention. This project is under development and has not yet been completed. Some functions are still being improved. Videos, pictures and documents will be released soon!

**Comment by liuzhenboo** [comment]
> Hi liuzhenbo,
> Big fan of your work. Is there any ducument about your work? Maybe a demo.
> Many thanks!

Thank you for your attention. This project is under development and has not yet been completed. Some functions are still being improved. Videos, pictures and documents will be released soon!
